version: '3.8'
services:
  commercial-sandbox-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "npm run migrate &&
             npm run seed:all &&
             npm start"
    env_file:
      - .env   
    ports:
      - "3030:3030"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

